class PathReliabilityParams:
    # from selfdrive/modeld/fill_model_msg.py
    LANE_RELIABILITY_SCALE = 1.5
    LANE_LINES_BOOST = 1.2
    LANE_LINES_REDUCE_ONE = 0.8
    LANE_LINES_REDUCE_NONE = 0.5
    LANE_LINES_MIN_PROB_ONE = 0.3
    LANE_LINES_MIN_PROB_NONE = 0.1

    # from selfdrive/controls/lib/longitudinal_planner.py
    PATH_RELIABILITY_MODERATE = 0.7
    ACCEL_REDUCTION_MODERATE = 0.85
    BRAKE_AGGRESSION_MODERATE = 0.90
    PATH_RELIABILITY_LOW = 0.5
    ACCEL_REDUCTION_LOW = 0.7
    BRAKE_AGGRESSION_LOW = 0.8
    ACCEL_RATE_LIMIT_LOW_RELIABILITY = 0.03

    # from selfdrive/controls/lib/longitudinal_planner.py
    SAFETY_SCORE_DEGRADED = 0.6
    SAFETY_SCORE_CRITICAL = 0.3
    SAFETY_FACTOR_CRITICAL = 0.5
    SAFETY_SCORE_HIGH_RISK = 0.5
    SAFETY_FACTOR_HIGH_RISK = 0.65
    SAFETY_FACTOR_MODERATE_RISK = 0.8
    SAFETY_FACTOR_PATH_RELIABILITY_LOW = 0.7
    SAFETY_FACTOR_PATH_RELIABILITY_VERY_LOW = 0.5

    # from selfdrive/controls/lib/latcontrol_pid.py
    PATH_RELIABILITY_LAT_THRESHOLD = 0.7
    RELIABILITY_FACTOR_BASE = 0.8
    RELIABILITY_FACTOR_MULTIPLIER = 0.2
