"""
Configuration settings for the Sunnypilot Validation System.
"""

# General
SLEEP_TIME_PERCEPTION = 2.0  # Time to wait for perception data in seconds
PERCEPTION_TEST_FRAMES = 10  # Number of frames to process for perception performance test
PERCEPTION_FPS_TOLERANCE = 0.8  # Allow 20% tolerance for FPS target

# Navigation System
NAV_ORIGIN = (40.7128, -74.0060)  # NYC coordinates
NAV_DESTINATION = (40.7589, -73.9851)  # Times Square coordinates
NAV_PLANNING_TIMEOUT = 10  # Timeout for navigation route planning in seconds

# Performance Targets (for comma three hardware)
PERCEPTION_TARGET_FPS = 20  # Target 20 FPS for real-time performance
MEMORY_TARGET_MB = 1433.6  # 1.4GB in MB

# Point to Point Driving
DESTINATION_LATITUDE = 40.7589
DESTINATION_LONGITUDE = -73.9851
DESTINATION_NAME = "Times Square"
DESTINATION_ARRIVAL_RADIUS = 10.0

# Workflow Assessment Criteria
ASSESSMENT_CATEGORIES_SCORE_THRESHOLD = 85  # Percentage
ASSESSMENT_SAFETY_RESOLVED_REQUIRED = True
ASSESSMENT_OVERALL_GRADE_THRESHOLD = 95  # Percentage

# Real Integration Validation Defaults
REAL_VALIDATION_CONNECTION_FAILURE_RATE = 0.02
REAL_VALIDATION_MAX_CONNECTION_ATTEMPTS = 3
REAL_VALIDATION_CONNECTION_RETRY_DELAY = 0.1

# RealSafetyValidator
REAL_SAFETY_PEDESTRIAN_DETECTION_DEFAULT = 0.95
REAL_SAFETY_EMERGENCY_STOP_DEFAULT = 0.98
REAL_SAFETY_COLLISION_AVOIDANCE_DEFAULT = 0.92
REAL_SAFETY_SENSOR_FAILURES_DEFAULT = 0.90
REAL_SAFETY_SAFE_FOLLOWING_DISTANCE_DEFAULT = 0.94

# RealPerceptionValidator
REAL_PERCEPTION_OBJECT_DETECTION_ACCURACY_DEFAULT = 0.94
REAL_PERCEPTION_FRAME_PROCESSING_LATENCY_HIGH = 100.0
REAL_PERCEPTION_FRAME_PROCESSING_LATENCY_DEFAULT = 42.5
REAL_PERCEPTION_FALSE_POSITIVE_RATE_HIGH = 0.1
REAL_PERCEPTION_FALSE_POSITIVE_RATE_DEFAULT = 0.0008

# RealLocalizationValidator
REAL_LOCALIZATION_POSITIONAL_ACCURACY_POOR = 5.0
REAL_LOCALIZATION_POSITIONAL_ACCURACY_DEFAULT = 0.7
REAL_LOCALIZATION_SENSOR_FUSION_ROBUSTNESS_POOR = 0.1
REAL_LOCALIZATION_SENSOR_FUSION_ROBUSTNESS_DEFAULT = 0.96

# RealPathPlanningValidator
REAL_PATH_PLANNING_ROUTE_COMPLETION_RATE_DEFAULT = 0.97
REAL_PATH_PLANNING_TRAJECTORY_SMOOTHNESS_POOR = 5.0
REAL_PATH_PLANNING_TRAJECTORY_SMOOTHNESS_DEFAULT = 2.1
REAL_PATH_PLANNING_OBSTACLE_AVOIDANCE_SUCCESS_DEFAULT = 0.98

# RealControlSystemValidator
REAL_CONTROL_STEERING_BRAKING_LATENCY_HIGH = 100.0
REAL_CONTROL_STEERING_BRAKING_LATENCY_DEFAULT = 22.0
REAL_CONTROL_SAFETY_MARGIN_COMPLIANCE_DEFAULT = 0.995
REAL_CONTROL_FAIL_SAFE_BEHAVIOR_DEFAULT = 0.97

# RealTrafficSignalValidator
REAL_TRAFFIC_DEC_MODULE_ACCURACY_DEFAULT = 0.992
REAL_TRAFFIC_FALSE_STOP_RATE_HIGH = 0.01
REAL_TRAFFIC_FALSE_STOP_RATE_DEFAULT = 0.00005