import os

def get_ui_cflags(target, testing):
  cflags = [
    '-DASSET_FONTS',
    '-Wno-sign-compare',
    '-Wno-gnu-zero-variadic-macro-arguments',
  ]

  cflags += [
    '-DUSE_RAYLIB',
  ]

  return cflags

def get_ui_common_sources():
  return [
    "ui.cc",
    "soundd.py",
  ]

def get_ui_sources(target, testing):
  sources = get_ui_common_sources()

  sources += [
    "raylib/raylib_window.cc",
    "raylib/raylib_ui_state.cc",
    "raylib/raylib_ui_state_full.cc",
    "raylib/raylib_ui_window.cc",
    "raylib/raylib_ui_components.cc",
    "raylib/raylib_settings_components.cc",
    "raylib/raylib_extra_components.cc",
    "raylib/raylib_font_manager.cc",
    "raylib/raylib_texture_manager.cc",
    "raylib/resource_manager.cc",
  ]

  return sources

def get_ui_incflags():
  incflags = [
    ".",
    "../",
    "../../",
    "../../../",
  ]

  # Add raylib include path
  incflags += [
    "../third_party/raylib/include",
  ]

  return incflags

def get_ui_libs(target, testing):
  libs = []

  libs += [
    "raylib",
    "pthread",
    "m",
    "dl",
    "GL",
    "X11",
    "Xrandr",
    "Xinerama",
    "Xi",
    "Xxf86vm",
    "Xcursor",
    "rt",
    "dl",
    "c",
    "m",
  ]

  return libs